export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_LOADING_SUCCESS = "PRODUCT_LOADING_SUCCESS";
export const PRODUCT_LOADING_ERROR = "PRODUCT_LOADING_ERROR";